version: '3.7'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: drsdb
      MYSQL_USER: nnay
      MYSQL_PASSWORD: 2001
      MYSQL_ROOT_PASSWORD: 2001
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --bind-address=0.0.0.0

