# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: nany
      MONGO_INITDB_ROOT_PASSWORD: 2001

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: nany
      ME_CONFIG_MONGODB_ADMINPASSWORD: 2001
      ME_CONFIG_MONGODB_URL: mongodb://nany:2001@mongo:27017/
      ME_CONFIG_BASICAUTH: false
